### ISSUE TITLE
No docs/ a few questions

### ISSUE THREAD

**Issue by Algomorph** [ridgeback/ridgeback_simulator#2]
Dear ridgeback_simulator Authors,

While we are awaiting for our first Ridgeback platform to arrive to use with the Baxter robot, we'd like to the development using simulation. 
Since there is no documentation for ridgeback_gazebo as of yet (http://docs.ros.org/indigo/api/ridgeback_gazebo/html/), could you give us a few pointers to get us started?

We have two questions right now:
1) What are the basic steps needed to integrate baxter simulator with ridgeback_gazebo and what would be a reasonable transform to use between the simulated baxter & ridgeback platform, as a default?

2) What are the basic steps needed to control the simulated ridgeback from a basic [action server](http://wiki.ros.org/action/fullsearch/actionlib_tutorials/Tutorials/Writing%20a%20Simple%20Action%20Server%20using%20the%20Execute%20Callback%20%28Python%29?action=fullsearch&context=180&value=linkto%3A%22actionlib_tutorials%2FTutorials%2FWriting+a+Simple+Action+Server+using+the+Execute+Callback+%28Python%29%22)?

Kind regards,
Greg

**Comment by tonybaltovski** [comment]
Hi Greg,

There is usually not any documentation here for simulation packages since there is no API.  We took a stab at integrating the Baxter on the Ridgeback [here](https://github.com/ridgeback/ridgeback_baxter) but there were some issues.  The pending PR is a good starting point.   

I believe it would be reasonable.  However, since you do have the platform, testing on it would be the most accurate.  
Using move_base to send a navigation goal would be the most straight forward as shown [here](http://wiki.ros.org/navigation/Tutorials/SendingSimpleGoals).  It can be done with purely odometry like the [Husky](https://github.com/husky/husky/blob/indigo-devel/husky_navigation/launch/move_base_mapless_demo.launch)

If you have any more questions, feel free to ask!

Regards,
Tony
